main: me.tazadejava.main.TeamChallengeMCGD
name: TeamChallengeMCGD
api-version: 1.13
version: 1.1
permissions:
  teamchallenge.lead:
    description: Op commands.
    default: op
commands:
  gm:
    description: Change gamemode.
    permission: teamchallenge.lead
  mcgd:
    description: Main command for MCGD development
    permission: teamchallenge.lead
  challenge:
    description: Main challenge command.